### ISSUE TITLE
wildfly deployment of graphQL server

### ISSUE THREAD

**Issue by zerounix** [camunda/camunda-bpm-graphql#13]
Hi guys,

I tried running the .war file on a fresh camunda wildfly installation which actually failed because of a missing dependency to camunda bpm engine jboss module. I added this via a jboss-deployment-structure.xml and finally got it working.

Do you have any plans to add this feature, like via a build profile or something, in the future?

I read that you have plans to have some sample ui application, is there already something to have a peek at, because I really plan to use graphql with react for our next workflow application?

**Comment by hloydl** [comment]
Hi @zerounix 
we never tested camunda-bpm-graphql on a Wildfly installation, pretty much sticked to Tomcat for no special reason, just to stay focused. Great to hear that you got it working. We do not have any plans yet to add this feature. We would appreciate your contribution so that other Wildfly installations could benefit from your findings.  
Regarding a sample ui application - well, yes, we are preparing a show case "Camunda GraphQL Tasklist" based on React and the [Apollo client](http://dev.apollodata.com/core/apollo-client-api.html#apollo-client). We can render forms 

- based on [react-jsonschema-form](https://mozilla-services.github.io/react-jsonschema-form/) to just try a nice forms DSL
- based on [Form Data Metadata provided in the BPMN 2.0 XML](https://docs.camunda.org/manual/7.7/user-guide/task-forms/#generated-task-forms) defined by the [Camunda Modeller](https://camunda.org/download/modeler/). 

Anyway, what we struggle with is the rendering of task forms based on React (or let it be Angular 2) inside the existing Camunda Tasklist or our "Camunda GraphQL Tasklist". The problem is the loading and execution of React components or JavaScript during runtime without exposing a potential security hole (i.e. using the evil Javascript eval()-function). Maybe there is no simple solution, maybe it's so simple we do not see it yet...
